services:
  test_db:
    container_name: test_db
    image: influxdb:3-core
    ports:
      - 8182:8181
    command:
      - influxdb3
      - serve
      - --without-auth
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - influxdb-test-data:/var/lib/influxdb3/data
    user: "0"
volumes:
  influxdb-test-data:
